// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareInvest.CoreAPI;

namespace ShareInvest.Migrations
{
    [DbContext(typeof(CoreApiDbContext))]
    partial class CoreApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.6.20312.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShareInvest.Models.Codes", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("MaturityMarketCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("ShareInvest.Models.Days", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Date");

                    b.HasIndex("Code");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("ShareInvest.Models.Futures", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.HasIndex("Code");

                    b.ToTable("Futures");
                });

            modelBuilder.Entity("ShareInvest.Models.Options", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.HasIndex("Code");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("ShareInvest.Models.Privacy", b =>
                {
                    b.Property<string>("Security")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecuritiesAPI")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("SecurityAPI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Security");

                    b.ToTable("Privacies");
                });

            modelBuilder.Entity("ShareInvest.Models.Stocks", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.HasIndex("Code");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ShareInvest.Models.Days", b =>
                {
                    b.HasOne("ShareInvest.Models.Codes", "Codes")
                        .WithMany("Days")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareInvest.Models.Futures", b =>
                {
                    b.HasOne("ShareInvest.Models.Codes", "Codes")
                        .WithMany("Futures")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareInvest.Models.Options", b =>
                {
                    b.HasOne("ShareInvest.Models.Codes", "Codes")
                        .WithMany("Options")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareInvest.Models.Stocks", b =>
                {
                    b.HasOne("ShareInvest.Models.Codes", "Codes")
                        .WithMany("Stocks")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
